#!/usr/bin/env bash

##########################################
# System
##########################################

# search current directory
function ff(){
  l | rg "$1"
}

# Create a new directory and enter it
function mk() {
  mkdir -p "$@" && cd "$@" || exit
}

function len() {
  var="$1"
  echo ${#var}
}

# copy directory
function cpdir() {
  cp -R "$1" "$2"
}

# Move directory
function mvdir() {
  mv -R "$1" "$2"
}

# counts whateva
function count() {
  "$1" | wc -l
}

# Prints how many files in a dir
function dirsize() {
  du -sh "$1"
}

# Python
function misepy() {
  cat > .mise.toml << EOL
[tools]
python = "3.11" # [optional] will be used for the venv

[env]
_.python.venv = { path = ".venv", create = true } # create the venv if it doesn't exist
EOL
}

function pyvenv() {
  python3 -m venv venv && \
    source "venv/bin/activate"
}

# Creates new brew dump file. If one exists this will delete it.
function brdump() {
  BRFILE="$HOME/dotfiles/Brewfile"
  if [ -f "$BRFILE" ]; then
    rm "$BRFILE"
  fi
  brew bundle dump --file="$BRFILE"
}

function tmcolors() {
  for i in {0..255}; do
    printf "\x1b[38;5;${i}mcolour${i}\x1b[0m\n"
  done
}

function allup() {
  brud
  brup
  npmup
  vimup
  packerup
}

# use "${var:?}" https://www.shellcheck.net/wiki/SC2115
function godel(){
  echo "${GOPATH:?}/bin/${1:?}"
}

##########################################
# Random
##########################################

# how fast is program
function speed() {
  "$1" "$2" | pv > /dev/null
  # go run main.go | pv > /dev/null
}
