#!/usr/bin/env bash

##########################################
# System
##########################################

# Create a new directory and enter it
function mk() {
  mkdir -p "$@" && cd "$@" || exit
}

function len() {
  var="$1"
  echo ${#var}
}

# copy directory
function cpdir() {
  cp -R "$1" "$2"
}

# Move directory
function mvdir() {
  mv -R "$1" "$2"
}

# counts whateva
function count() {
  "$1" | wc -l
}

# Prints how many files in a dir
function dirsize() {
  du -sh "$1"
}

# git
ga() {
  git add .
  git commit -m "$1"
  echo -n "✅ commited, you all good homie 🫡"
}

gp() {
  git push -u origin main
  echo -n "pushin' 🅿️ homie"
}

am() {
  git add .
  git commit --amend --no-edit
  echo -n "amended brother 🙏"
}

# languages

function rtxpy() {
  printf "[tools]\n python = { version='3.10', virtualenv='.venv' }\n" >> .rtx.toml
}

function pyvenv() {
  python3 -m venv venv && \
  source "venv/bin/activate"
}

function pypyvenv() {
  pypy3 -m venv venv && \
  source "venv/bin/activate"
}

# Prints how many files in a dir
# function dirsize() {
#   find "$1" -type f | wc -l
# }

# Creates new brew dump file. If one exists this will delete it.
function brdump() {
  BRFILE="$HOME/.dotfiles/Brewfile"
  if [ -f "$BRFILE" ]; then
    rm "$BRFILE"
  fi
  brew bundle dump --file="$BRFILE"
}

function tmcolors() {
  for i in {0..255}; do
      printf "\x1b[38;5;${i}mcolour${i}\x1b[0m\n"
  done
}

function allup() {
  brud
  brup
  npmup
  vimup
  packerup
}

# use "${var:?}" https://www.shellcheck.net/wiki/SC2115
function godel(){
  echo "${GOPATH:?}/bin/${1:?}"
}

##########################################
# Random
##########################################

# how fast is program
function speed() {
  "$1" "$2" | pv > /dev/null
  # go run main.go | pv > /dev/null
}
