#!/usr/bin/env python3

"""Make all files in directory lowercase"""

import os
import sys


def main():
    args = sys.argv
    folder = args[1]

    for _, file in enumerate(os.listdir(folder)):
        src = f"{folder}/{file}"
        dst = f"{folder}/{file.lower()}"

        os.rename(src, dst)

if __name__ == "__main__":
    main()
