#!/bin/bash

# ez git commands

case $1 in
  add | a)
    git add .
    git commit -m "$2"
    echo -n "✅ commited, you all good homie 🫡"
    ;;
  push | p)
    git push -u origin main
    echo -n "pushin' 🅿️ homie"
    ;;
  "add-push" | ap)
    git add .
    git commit -m "$2"
    git push -u origin main
    echo -n "pushin' 🅿️ homie"
    ;;
  lb)
    # last branch
    git checkout -
    ;;
  nb)
    # new branch
    git checkout -b "$2"
    ;;
  db)
    # delete branch
    git branch -D "$2"
    ;;
  amen)
    git add .
    git commit --amend --no-edit
    echo -n "amended brother 🙏"
    ;;
  reset | r)
    git reset
    git checkout .
    echo -n "all done"
    ;;
  ro)
    # reset origin/current branch
    git reset --hard @{u}
    echo -n "origin now local"
    ;;
  clear)
    git rm -rf --cached .
    echo -n "files cleared"
    ;;
  help | h)
    echo "dont worry lad 🤙"
    echo "📝 commands are...
    add | a - add all and commit
    push | p - push commit to remote
    add-push | ap - combo of above
    lb - last branch
    nb ... - new branch 'name'
    db - delete branch
    amen - amend commit with new changes
    reset | r - reset all unstaged changes
    ro - reset hard to origin
    clear - clear cached files
    "
esac
